version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
